// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CheckAudioPermissions(arg1:string):Promise<Record<string, any>>;

export function CreateFolder(arg1:string,arg2:string):Promise<domain.Folder>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<domain.Note>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<domain.Prompt>;

export function DeleteFolder(arg1:string,arg2:boolean):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function ExecutePromptOnContent(arg1:string,arg2:string):Promise<domain.PromptExecutionResult>;

export function ExecutePromptOnContentStream(arg1:string,arg2:string):Promise<void>;

export function ExecutePromptOnNote(arg1:string,arg2:string):Promise<domain.PromptExecutionResult>;

export function ExecutePromptOnNoteStream(arg1:string,arg2:string):Promise<void>;

export function GenerateText(arg1:string,arg2:string):Promise<domain.LLMResponse>;

export function GenerateTextStream(arg1:string,arg2:string):Promise<void>;

export function GenerateTextStreamWithOptions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function GenerateTextWithOptions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<domain.LLMResponse>;

export function GetAllFolders():Promise<Array<domain.Folder>>;

export function GetAllNotes():Promise<Array<domain.Note>>;

export function GetAllPrompts():Promise<Array<domain.Prompt>>;

export function GetAudioDevices():Promise<Array<domain.AudioDevice>>;

export function GetAudioSources():Promise<Array<Record<string, any>>>;

export function GetAudioStatus():Promise<Record<string, any>>;

export function GetCurrentAudioSource():Promise<string>;

export function GetFolderPath(arg1:string):Promise<Array<domain.Folder>>;

export function GetLLMStatus():Promise<Record<string, any>>;

export function GetMixerConfig():Promise<Record<string, any>>;

export function GetNote(arg1:string):Promise<domain.Note>;

export function GetPrompt(arg1:string):Promise<domain.Prompt>;

export function GetSTTStatus():Promise<Record<string, any>>;

export function GetStreamingSupport():Promise<boolean>;

export function IsRecording():Promise<boolean>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function RequestAudioPermissions(arg1:string):Promise<void>;

export function SetAudioSource(arg1:string):Promise<void>;

export function SetMixerConfig(arg1:number,arg2:number,arg3:string):Promise<void>;

export function StartVoiceRecording():Promise<void>;

export function StartVoiceRecordingWithSource(arg1:string):Promise<void>;

export function StopVoiceRecording():Promise<domain.TranscriptionResult>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLLMConfig(arg1:domain.LLMConfig):Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<void>;
