// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAudioPermissions(arg1) {
  return window['go']['main']['App']['CheckAudioPermissions'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function ExecutePromptOnContent(arg1, arg2) {
  return window['go']['main']['App']['ExecutePromptOnContent'](arg1, arg2);
}

export function ExecutePromptOnContentStream(arg1, arg2) {
  return window['go']['main']['App']['ExecutePromptOnContentStream'](arg1, arg2);
}

export function ExecutePromptOnNote(arg1, arg2) {
  return window['go']['main']['App']['ExecutePromptOnNote'](arg1, arg2);
}

export function ExecutePromptOnNoteStream(arg1, arg2) {
  return window['go']['main']['App']['ExecutePromptOnNoteStream'](arg1, arg2);
}

export function GenerateText(arg1, arg2) {
  return window['go']['main']['App']['GenerateText'](arg1, arg2);
}

export function GenerateTextStream(arg1, arg2) {
  return window['go']['main']['App']['GenerateTextStream'](arg1, arg2);
}

export function GetAPILLMModels(arg1, arg2) {
  return window['go']['main']['App']['GetAPILLMModels'](arg1, arg2);
}

export function GetAllFolders() {
  return window['go']['main']['App']['GetAllFolders']();
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetAllPrompts() {
  return window['go']['main']['App']['GetAllPrompts']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetAudioSources() {
  return window['go']['main']['App']['GetAudioSources']();
}

export function GetAudioStatus() {
  return window['go']['main']['App']['GetAudioStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentAudioSource() {
  return window['go']['main']['App']['GetCurrentAudioSource']();
}

export function GetFolderPath(arg1) {
  return window['go']['main']['App']['GetFolderPath'](arg1);
}

export function GetLLMModels() {
  return window['go']['main']['App']['GetLLMModels']();
}

export function GetLLMStatus() {
  return window['go']['main']['App']['GetLLMStatus']();
}

export function GetMixerConfig() {
  return window['go']['main']['App']['GetMixerConfig']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetSTTModels() {
  return window['go']['main']['App']['GetSTTModels']();
}

export function GetSTTStatus() {
  return window['go']['main']['App']['GetSTTStatus']();
}

export function GetStreamingSupport() {
  return window['go']['main']['App']['GetStreamingSupport']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function RequestAudioPermissions(arg1) {
  return window['go']['main']['App']['RequestAudioPermissions'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchNotes(arg1, arg2) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2);
}

export function SetAudioSource(arg1) {
  return window['go']['main']['App']['SetAudioSource'](arg1);
}

export function SetMixerConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMixerConfig'](arg1, arg2, arg3);
}

export function StartVoiceRecording() {
  return window['go']['main']['App']['StartVoiceRecording']();
}

export function StartVoiceRecordingWithSource(arg1) {
  return window['go']['main']['App']['StartVoiceRecordingWithSource'](arg1);
}

export function StopTextStream() {
  return window['go']['main']['App']['StopTextStream']();
}

export function StopVoiceRecording() {
  return window['go']['main']['App']['StopVoiceRecording']();
}

export function UpdateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2, arg3);
}

export function UpdateLLMConfig(arg1) {
  return window['go']['main']['App']['UpdateLLMConfig'](arg1);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}
