// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllFolders() {
  return window['go']['main']['App']['GetAllFolders']();
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetFolderPath(arg1) {
  return window['go']['main']['App']['GetFolderPath'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetSTTStatus() {
  return window['go']['main']['App']['GetSTTStatus']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function StartVoiceRecording() {
  return window['go']['main']['App']['StartVoiceRecording']();
}

export function StopVoiceRecording() {
  return window['go']['main']['App']['StopVoiceRecording']();
}

export function UpdateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2, arg3);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}
