// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<domain.Folder>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<domain.Note>;

export function DeleteFolder(arg1:string,arg2:boolean):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetAllFolders():Promise<Array<domain.Folder>>;

export function GetAllNotes():Promise<Array<domain.Note>>;

export function GetFolderPath(arg1:string):Promise<Array<domain.Folder>>;

export function GetNote(arg1:string):Promise<domain.Note>;

export function GetSTTStatus():Promise<Record<string, any>>;

export function IsRecording():Promise<boolean>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function StartVoiceRecording():Promise<void>;

export function StopVoiceRecording():Promise<main.TranscriptionResult>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<void>;
